lsportal:
  oddsingestor:
    pregame:
      queueName: "_2541_"
      
    ingame:
      username: "christian.marko@statsperform.com"
      password: "cf436b45g"
      virtualHost: "Customers"
      host: "inplay-rmq.lsports.eu"
      port: 5672
      connectionTimeout: 15000
      heartbeatInterval: 30000
      queueName: "_2542_"
      
spring:
  rabbitmq:
    host: "prematch-rmq.lsports.eu"
    port: 5672
    username: "christian.marko@statsperform.com"
    password: "cf436b45g"
    virtualHost: "Customers"